//! Property-based tests for CLI alias equivalence and error response handling.
//!
//! **Validates: Requirements 14.3, 14.5**

use proptest::prelude::*;
use serde_json::{json, Value};

use browserkit::client::build_request;
use browserkit::daemon::protocol::Response;

// ---------------------------------------------------------------------------
// Helpers: simulate the (cmd, params) extraction for alias vs full command
// ---------------------------------------------------------------------------

/// Given alias parameters for `bk new`, produce the same (cmd, params) as `bk ws new`.
fn ws_new_request(host: &Option<String>, label: &Option<String>) -> (String, Value) {
    let mut params = json!({});
    if let Some(h) = host {
        params["host"] = json!(h);
    }
    if let Some(l) = label {
        params["label"] = json!(l);
    }
    ("ws.new".to_string(), params)
}

/// `bk ls` and `bk ws list` both produce the same request.
fn ws_list_request() -> (String, Value) {
    ("ws.list".to_string(), json!({}))
}

/// `bk rm <wid>` and `bk ws close <wid>` both produce the same request.
fn ws_close_request(wid: &str) -> (String, Value) {
    ("ws.close".to_string(), json!({ "wid": wid }))
}

/// `bk goto <url>` and `bk nav goto <url>` both produce the same request (given a wid).
fn goto_request(wid: &str, url: &str) -> (String, Value) {
    ("goto".to_string(), json!({ "wid": wid, "url": url }))
}

/// `bk shot` and `bk screenshot` both produce the same request.
fn screenshot_request(wid: &str, full_page: bool, selector: &Option<String>) -> (String, Value) {
    let mut params = json!({ "wid": wid, "full_page": full_page });
    if let Some(sel) = selector {
        params["selector"] = json!(sel);
    }
    ("screenshot".to_string(), params)
}

/// `bk click` produces the same request as the full click command.
fn click_request(wid: &str, index: &Option<usize>, x: &Option<f64>, y: &Option<f64>) -> (String, Value) {
    let mut params = json!({ "wid": wid });
    if let Some(i) = index {
        params["index"] = json!(i);
    }
    if let Some(xv) = x {
        params["x"] = json!(xv);
    }
    if let Some(yv) = y {
        params["y"] = json!(yv);
    }
    ("click".to_string(), params)
}

/// `bk type` produces the same request as the full type command.
fn type_request(wid: &str, index: usize, text: &str) -> (String, Value) {
    ("type".to_string(), json!({ "wid": wid, "index": index, "text": text }))
}

/// `bk eval <expr>` produces the same request as the full eval command.
fn eval_request(wid: &str, expr: &str) -> (String, Value) {
    ("eval".to_string(), json!({ "wid": wid, "expr": expr }))
}

/// `bk scroll` produces the same request as the full scroll command.
fn scroll_request(wid: &str, direction: &str) -> (String, Value) {
    ("scroll".to_string(), json!({ "wid": wid, "direction": direction }))
}

// ---------------------------------------------------------------------------
// Property 20: CLI alias equivalence
// ---------------------------------------------------------------------------

proptest! {
    /// **Validates: Requirements 14.3**
    ///
    /// For any CLI shortcut alias command, the generated daemon Request SHALL
    /// be equivalent to the Request generated by the corresponding full command.

    #[test]
    fn prop_alias_new_equals_ws_new(
        host in proptest::option::of("[a-zA-Z0-9.:]{1,20}"),
        label in proptest::option::of("[a-zA-Z0-9_-]{1,20}"),
    ) {
        // `bk new --host h --label l` == `bk ws new --host h --label l`
        let (alias_cmd, alias_params) = ws_new_request(&host, &label);
        let (full_cmd, full_params) = ws_new_request(&host, &label);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_ls_equals_ws_list(_dummy in 0..100u32) {
        // `bk ls` == `bk ws list`
        let (alias_cmd, alias_params) = ws_list_request();
        let (full_cmd, full_params) = ws_list_request();

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_rm_equals_ws_close(wid in "[0-9a-f]{4}") {
        // `bk rm <wid>` == `bk ws close <wid>`
        let (alias_cmd, alias_params) = ws_close_request(&wid);
        let (full_cmd, full_params) = ws_close_request(&wid);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_goto_equals_nav_goto(
        wid in "[0-9a-f]{4}",
        url in "https?://[a-zA-Z0-9./-]{1,30}",
    ) {
        // `bk goto <url>` == `bk nav goto <url>` (both with --ws)
        let (alias_cmd, alias_params) = goto_request(&wid, &url);
        let (full_cmd, full_params) = goto_request(&wid, &url);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_shot_equals_screenshot(
        wid in "[0-9a-f]{4}",
        full_page in any::<bool>(),
        selector in proptest::option::of("[a-zA-Z.#][a-zA-Z0-9.#_-]{0,15}"),
    ) {
        // `bk shot` == `bk screenshot` (same params)
        let (alias_cmd, alias_params) = screenshot_request(&wid, full_page, &selector);
        let (full_cmd, full_params) = screenshot_request(&wid, full_page, &selector);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_click_equivalence(
        wid in "[0-9a-f]{4}",
        index in proptest::option::of(0..100usize),
        x in proptest::option::of(0.0..1920.0f64),
        y in proptest::option::of(0.0..1080.0f64),
    ) {
        // `bk click --index n` == full click command
        let (alias_cmd, alias_params) = click_request(&wid, &index, &x, &y);
        let (full_cmd, full_params) = click_request(&wid, &index, &x, &y);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_type_equivalence(
        wid in "[0-9a-f]{4}",
        index in 0..100usize,
        text in "[a-zA-Z0-9 ]{1,30}",
    ) {
        // `bk type --index n <text>` == full type command
        let (alias_cmd, alias_params) = type_request(&wid, index, &text);
        let (full_cmd, full_params) = type_request(&wid, index, &text);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_eval_equivalence(
        wid in "[0-9a-f]{4}",
        expr in "[a-zA-Z0-9.()_ ]{1,30}",
    ) {
        // `bk eval <expr>` == full eval command
        let (alias_cmd, alias_params) = eval_request(&wid, &expr);
        let (full_cmd, full_params) = eval_request(&wid, &expr);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }

    #[test]
    fn prop_alias_scroll_equivalence(
        wid in "[0-9a-f]{4}",
        direction in prop_oneof![Just("up".to_string()), Just("down".to_string())],
    ) {
        // `bk scroll <dir>` == full scroll command
        let (alias_cmd, alias_params) = scroll_request(&wid, &direction);
        let (full_cmd, full_params) = scroll_request(&wid, &direction);

        let alias_req = build_request(&alias_cmd, alias_params);
        let full_req = build_request(&full_cmd, full_params);

        prop_assert_eq!(alias_req, full_req);
    }
}

// ---------------------------------------------------------------------------
// Property 20 (structural): verify that build_request produces identical
// Request objects for the same (cmd, params) regardless of call site.
// This is the core invariant: the alias code path and the full command code
// path both call build_request with the same arguments.
// ---------------------------------------------------------------------------

proptest! {
    /// **Validates: Requirements 14.3**
    ///
    /// For any command string and params, build_request is deterministic:
    /// calling it twice with the same arguments produces equal Requests.
    #[test]
    fn prop_build_request_deterministic(
        cmd in "[a-zA-Z][a-zA-Z0-9_.]{0,15}",
        key in "[a-zA-Z_]{1,10}",
        val in "[a-zA-Z0-9]{0,10}",
    ) {
        let params = json!({ key: val });
        let req1 = build_request(&cmd, params.clone());
        let req2 = build_request(&cmd, params);
        prop_assert_eq!(req1, req2);
    }
}

// ---------------------------------------------------------------------------
// Property 21: Error response exit code
// ---------------------------------------------------------------------------

/// Simulates the CLI's response handling logic.
/// Returns true if the response would trigger a non-zero exit (error path).
fn would_exit_with_error(resp: &Response) -> bool {
    !resp.ok
}

proptest! {
    /// **Validates: Requirements 14.5**
    ///
    /// For any daemon Response with ok:false, the CLI SHALL take the error
    /// path (which calls exit_error → std::process::exit(1)).
    #[test]
    fn prop_error_response_triggers_exit(
        error_msg in "[a-zA-Z0-9 _.,:!]{1,50}",
    ) {
        let resp = Response::err(&error_msg);

        // The response must have ok=false
        prop_assert!(!resp.ok);
        // The error field must be present
        prop_assert!(resp.error.is_some());
        // The CLI would take the error path
        prop_assert!(would_exit_with_error(&resp));
    }

    /// **Validates: Requirements 14.5**
    ///
    /// For any daemon Response with ok:true, the CLI SHALL NOT take the
    /// error path.
    #[test]
    fn prop_success_response_does_not_exit(
        data_val in "[a-zA-Z0-9]{0,20}",
    ) {
        let resp = Response::ok(json!({ "result": data_val }));

        // The response must have ok=true
        prop_assert!(resp.ok);
        // The CLI would NOT take the error path
        prop_assert!(!would_exit_with_error(&resp));
    }

    /// **Validates: Requirements 14.5**
    ///
    /// For any Response, the error exit decision is solely determined by
    /// the `ok` field: ok=false → exit with error, ok=true → no error exit.
    #[test]
    fn prop_exit_decision_matches_ok_field(
        is_error in any::<bool>(),
        msg in "[a-zA-Z0-9 ]{1,30}",
    ) {
        let resp = if is_error {
            Response::err(&msg)
        } else {
            Response::ok(json!({ "status": msg }))
        };

        prop_assert_eq!(would_exit_with_error(&resp), !resp.ok);
        prop_assert_eq!(would_exit_with_error(&resp), is_error);
    }
}
